#!/bin/bash

count=0
for i in 32 64 128
do 
	for j in 1 2 4 8
	do   
 let count++
./build/ARM/gem5.opt -d SCRIPT/FINAL_TOTAL/HMMER/spechmmer_"$count" configs/example/se.py --cpu-type=MinorCPU --caches --l2cache --l1d_size="$i"kB --l1i_size=64kB --l2_size=512kB --l1i_assoc=$j --l1d_assoc=1 --l2_assoc=2 --cacheline_size=64 --cpu-clock=1GHz -c spec_cpu2006/456.hmmer/src/spechmmer -o "--fixed 0 --mean 325 --num 45000 --sd 200 --seed 0 spec_cpu2006/456.hmmer/data/bombesin.hmm" -I 100000000

	done

done 
