#!/bin/bash

count=0
for i in 16 32 64 128
do  
	for j in 256 512 1024 2048 4096
	do  
 let count++
./build/ARM/gem5.opt -d SCRIPT/FINAL_TOTAL/BZIP/specbzip_"$count" configs/example/se.py --cpu-type=MinorCPU --caches --l2cache --l1d_size=32kB --l1i_size=64kB --l2_size="$j"kB --l1i_assoc=1 --l1d_assoc=1 --l2_assoc=2 --cacheline_size=$i --cpu-clock=1GHz -c spec_cpu2006/401.bzip2/src/specbzip -o "spec_cpu2006/401.bzip2/data/input.program 10" -I 100000000

	done
done



 
 
